name: Run React and Go App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Run app
        run: docker run -p 3000:3000 jjwaksmanski/aimeetingassist
